site_name: Millennium Machines Milo V1.5
site_dir: .
nav:
  - Home: index.md
  - Sourcing Guide: bom/sourcing_guide.md
  - Printing Guide: printing/print_guide.md
  - Assembly Manual:
      - Introduction: assembly_manual/chapters/introduction.md
      - Acknowledgements: assembly_manual/chapters/acknowledgements.md
      - Hardware Reference: assembly_manual/chapters/hardware_reference.md
      - Table Assembly: assembly_manual/chapters/table_assembly.md
      - X-Axis Assembly: assembly_manual/chapters/x_axis_assembly.md
      - Y-Axis Assembly: assembly_manual/chapters/y_axis_assembly.md
      - Z-Axis Assembly: assembly_manual/chapters/z_axis_assembly.md

#extra_css:
#  - stylesheets/extra.css

theme:
  name: material
  font:
    text: Roboto
  icon:
    logo: fontawesome/solid/industry
  palette:
    scheme: slate
    primary: red


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg